CREATE TABLE users (
    _id SERIAL PRIMARY KEY,
    id VARCHAR(50),
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    location_city VARCHAR(50) NOT NULL,
    location_country VARCHAR(50) NOT NULL,
    location_state VARCHAR(50) NOT NULL,
    location_latitude NUMERIC(6, 4) NOT NULL,
    location_longitude NUMERIC(7, 4) NOT NULL,
    location_postcode VARCHAR(50),
    location_street_info VARCHAR(100),
    email VARCHAR(100) NOT NULL,
    gender CHAR(1) NOT NULL,
    login_uuid VARCHAR(50) NOT NULL,
    login_username VARCHAR(50) NOT NULL,
    login_password VARCHAR(50) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    cell VARCHAR(50) NOT NULL,
    date_of_birth TIMESTAMPTZ NOT NULL,
    age INT NOT NULL,
    date_of_registration TIMESTAMPTZ NOT NULL,
    photo_link TEXT NOT NULL,
    extract_time TIMESTAMP NOT NULL,
    country_iso2 CHAR(2) NOT NULL,
    normalized_phone VARCHAR(50) NOT NULL,
    normalized_cell VARCHAR(50) NOT NULL,
    year_of_registration INT NOT NULL,
    month_of_registration INT NOT NULL,
    day_of_registration INT NOT NULL,
    password_length INT NOT NULL,
    login_length INT NOT NULL,
    transform_timestamp TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
